CREATE SEQUENCE IF NOT EXISTS item_id_seq;

CREATE TABLE IF NOT EXISTS ITEMS(
	id INT PRIMARY KEY DEFAULT NEXTVAL('item_id_seq'),
	itemTypeID int NOT NULL REFERENCES ITEM_TYPES ON DELETE CASCADE,
	itemType varchar(255) NOT NULL,
	itemName varchar(255) NOT NULL
);

